### PR TITLE
Wbo 0.4

### PR DESCRIPTION
**Pull request by Nadezhda-n**

### CODE REVIEW

**Comment by rusefillc** [comment]
@Qwerty-OFF please review and approve

**Review by Qwerty-OFF — APPROVED** [review]
Looks good. Needs to be checked on the next board.

**Comment by rusefillc** [comment]
As a weird way forward we might bump only one of WBO modules on some dual-WBO boards. Open question if hellen-one framework would handle that properly.

**Comment by rusefillc** [comment]
See also #194

**Pull request merged**
